title: I am a random person.
logo: AWANG.png
description: This website was created 2024/12/3 18:37 when thinking of committing suicide.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
